<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="32" total="33" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Automation" duration-ms="110181" started-at="2018-02-01T22:14:46Z" finished-at="2018-02-01T22:16:36Z">
    <groups>
    </groups>
    <test name="TestScripts" duration-ms="110181" started-at="2018-02-01T22:14:46Z" finished-at="2018-02-01T22:16:36Z">
      <class name="com.testscripts.TestCases">
        <test-method status="PASS" signature="openApp()[pri:0, instance:com.testscripts.TestCases@10a035a0]" name="openApp" is-config="true" duration-ms="10502" started-at="2018-02-01T17:14:36Z" finished-at="2018-02-01T17:14:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method status="FAIL" signature="errorHandlingMetoMeRestriction()[pri:0, instance:com.testscripts.TestCases@10a035a0]" name="errorHandlingMetoMeRestriction" duration-ms="110162" started-at="2018-02-01T17:14:46Z" finished-at="2018-02-01T17:16:36Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerExceptionat com.library.Common.verifyElementPresent(Common.java:183)at com.businessfunctions.TransferPage.restictionsMetoMe(TransferPage.java:508)at com.testscripts.TestCases.errorHandlingMetoMeRestriction(TestCases.java:464)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- errorHandlingMetoMeRestriction -->
        <test-method status="PASS" signature="closeApp()[pri:0, instance:com.testscripts.TestCases@10a035a0]" name="closeApp" is-config="true" duration-ms="5859" started-at="2018-02-01T17:16:37Z" finished-at="2018-02-01T17:16:42Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- com.testscripts.TestCases -->
    </test> <!-- TestScripts -->
  </suite> <!-- Automation -->
</testng-results>
